import * as p from "@clack/prompts";
import pc from "picocolors";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ensureAuth } from "../steps/auth.js";
import { wrangler } from "../lib/wrangler.js";
import { execa } from "execa";

interface SetupState {
  projectName?: string;
  workerName?: string;
  workerUrl?: string;
  adminUrl?: string;
  accountId?: string;
  d1DatabaseId?: string;
  d1DatabaseName?: string;
  liffId?: string;
  botBasicId?: string;
  [key: string]: unknown;
}

function loadState(repoDir: string): SetupState | null {
  // setup.ts writes to `.line-harness-setup.json`. The earlier file name
  // (`.line-harness-config.json`) was a pre-rename leftover that caused the
  // update command to never find prior state and always re-prompt — leading
  // users to type the wrong name and target a non-existent Worker. Try the
  // canonical name first, then fall back for legacy installs.
  const candidates = [".line-harness-setup.json", ".line-harness-config.json"];
  for (const name of candidates) {
    const path = join(repoDir, name);
    if (!existsSync(path)) continue;
    try {
      return JSON.parse(readFileSync(path, "utf-8"));
    } catch {
      // corrupt file — try next candidate
    }
  }
  return null;
}

/**
 * The OSS wrangler.toml ships with placeholders (`YOUR_DEV_ACCOUNT_ID` /
 * `YOUR_DEV_D1_DATABASE_ID`) so it never leaks the upstream maintainer's IDs
 * into git history. setup.ts patches them in-place before `wrangler deploy`
 * and restores afterwards. The update flow must do the same — otherwise
 * `wrangler deploy` reads the placeholder verbatim and Cloudflare returns
 * `Could not route to /accounts/YOUR_DEV_ACCOUNT_ID/...`.
 *
 * Returns the original content so the caller can restore via
 * `restoreWranglerToml()` in a finally block.
 */
function patchWranglerToml(
  repoDir: string,
  accountId: string,
  databaseId?: string,
): string | null {
  const tomlPath = join(repoDir, "apps/worker/wrangler.toml");
  if (!existsSync(tomlPath)) return null;
  const original = readFileSync(tomlPath, "utf-8");
  let content = original.replace(
    /account_id\s*=\s*"[^"]*"/g,
    `account_id = "${accountId}"`,
  );
  if (databaseId) {
    content = content.replace(
      /database_id\s*=\s*"[^"]*"/g,
      `database_id = "${databaseId}"`,
    );
  }
  writeFileSync(tomlPath, content);
  return original;
}

function restoreWranglerToml(repoDir: string, original: string | null): void {
  if (original === null) return;
  const tomlPath = join(repoDir, "apps/worker/wrangler.toml");
  try {
    writeFileSync(tomlPath, original);
  } catch {
    // Best effort — user can `git -C ~/.line-harness checkout apps/worker/wrangler.toml`.
  }
}

/**
 * `apps/worker/.env` (VITE_LIFF_ID / VITE_BOT_BASIC_ID) is gitignored and
 * only written once, during the initial `setup.ts` run (see
 * deploy-worker.ts). It is NOT regenerated by this update flow, so if it's
 * ever missing — a fresh clone, a copy to a new machine/folder that skipped
 * dotfiles, a manual `rm .env` — `vite build` silently bakes an EMPTY
 * VITE_LIFF_ID into the client bundle. The resulting error only surfaces
 * when a friend taps a LIFF link and sees "LIFF ID がありません", by which
 * point the broken build has often already been live for a while.
 *
 * Regenerate it unconditionally from saved state before every rebuild so
 * this class of bug can't recur silently.
 */
function ensureWorkerEnv(repoDir: string, state: SetupState): void {
  if (!state.liffId) {
    p.log.warn(
      "状態ファイルに liffId が無いため apps/worker/.env を再生成できません。" +
        "LIFF ページで「LIFF ID がありません」と出る場合は、" +
        "apps/worker/.env に VITE_LIFF_ID=<liffId> を手動で追加してください。",
    );
    return;
  }
  const envPath = join(repoDir, "apps/worker/.env");
  const envContent = `VITE_LIFF_ID=${state.liffId}\nVITE_BOT_BASIC_ID=${state.botBasicId ?? ""}\n`;
  writeFileSync(envPath, envContent);
}

export async function runUpdate(repoDir: string): Promise<void> {
  p.intro(pc.bgCyan(pc.black(" LINE Harness アップデート ")));

  // Load saved config or ask for project name
  const savedState = loadState(repoDir);
  let projectName: string;

  if (savedState?.projectName) {
    projectName = savedState.projectName;
    p.log.success(`プロジェクト名: ${projectName}`);
  } else {
    const name = await p.text({
      message: "プロジェクト名（setup 時に指定した名前）",
      placeholder: "line-harness",
      defaultValue: "line-harness",
    });
    if (p.isCancel(name)) {
      p.cancel("アップデートをキャンセルしました");
      process.exit(0);
    }
    projectName = (name as string).trim() || "line-harness";
  }

  // Migration apply uses the D1 binding (DB name); fall back to project name.
  const dbName = savedState?.d1DatabaseName ?? projectName;

  await ensureAuth();

  // Patch wrangler.toml with the saved account_id / database_id so `wrangler
  // deploy` routes to the right Cloudflare account. Restored in finally below.
  let originalToml: string | null = null;
  if (savedState?.accountId) {
    originalToml = patchWranglerToml(
      repoDir,
      savedState.accountId,
      savedState.d1DatabaseId,
    );
  } else {
    p.log.warn(
      "状態ファイルに accountId が無いため wrangler.toml を patch しません。" +
        "デプロイが routing エラーになった場合は、apps/worker/wrangler.toml の" +
        "`account_id` を手動で実 ID に書き換えるか、再度 setup を実行してください。",
    );
  }

  const s = p.spinner();

  try {
    // Run pending migrations
    s.start("マイグレーション確認中...");
    try {
      await wrangler(
        ["d1", "migrations", "apply", dbName, "--remote"],
        { cwd: join(repoDir, "packages/db") },
      );
      s.stop("マイグレーション完了");
    } catch {
      s.stop("マイグレーション完了（変更なし）");
    }

    // 管理画面を先にビルドする。
    //
    // 管理画面は Worker と同一オリジン (<worker>/admin) から配信するので、
    // Worker の静的アセット (dist/client/admin) として同梱する必要がある。
    // Worker ビルド (vite build) が dist/client を作り直すため、
    //   1. 管理画面ビルド (apps/web/out を更新)
    //   2. Worker ビルド (vite build → sync-admin-assets.mjs)
    //   3. wrangler deploy
    // の順を崩さないこと。順序を逆にすると古い管理画面が配信される。
    //
    // 別オリジン (Cloudflare Pages) へのデプロイは廃止した。Worker とドメインが
    // 違うとセッション Cookie がサードパーティ Cookie 扱いになり、iOS Safari 等の
    // 既定設定でログインが維持できなかったのが理由。
    const webDir = join(repoDir, "apps/web");
    s.start("管理画面 再ビルド中...");
    await execa("pnpm", ["run", "build"], { cwd: webDir });
    s.stop("管理画面 再ビルド完了");

    // Redeploy Worker.
    //
    // `wrangler deploy` reads `dist/line_harness/wrangler.json` (vite build
    // 成果物) preferentially over the source `wrangler.toml`. If we patch
    // `wrangler.toml` but skip the vite build, wrangler will pick up the
    // STALE dist json (still containing `YOUR_DEV_ACCOUNT_ID`) and the deploy
    // fails routing. So we run the build step first, mirroring the
    // `vite build && wrangler deploy` pattern in apps/worker/package.json.
    const workerDir = join(repoDir, "apps/worker");
    if (savedState) ensureWorkerEnv(repoDir, savedState);

    s.start("Worker 再ビルド中（管理画面を同梱）...");
    await execa("pnpm", ["run", "build"], { cwd: workerDir });
    s.stop("Worker 再ビルド完了");

    s.start("Worker 再デプロイ中...");
    await wrangler(["deploy", "--name", projectName], { cwd: workerDir });
    s.stop("Worker 再デプロイ完了");

    const adminUrl = savedState?.workerUrl
      ? `${String(savedState.workerUrl).replace(/\/+$/, "")}/admin`
      : "https://<worker>/admin";
    p.log.success(`管理画面: ${adminUrl}`);

    p.outro(pc.green("アップデート完了！"));
  } finally {
    restoreWranglerToml(repoDir, originalToml);
  }
}
